name: get-version

on:
  push:
    tags:
      - 'v*'

env:
  LATEST_MASTER_HASH: ${{ github.sha }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.repository.default_branch }}
    - name: Show GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Get version
      run: |
        chmod +x get-version.py
        ./get-version.py ${{ env.LATEST_MASTER_HASH }}
    - name: Commit and push files
      run: |
        git config --global user.name 'github-actions-bot'
        git add version.txt
        git commit -m "Updating the version" || echo "No changes to version."
        git push
