name: get-version

on:
#   push:
#     tags:
#       - 'v*'

  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    # The default types are opened, synchronize, and reopened: we want to also
    # include ready_for_review
    types: [opened, synchronize, reopened, ready_for_review]
env:
  LATEST_MASTER_HASH: ${{ github.event.pull_request.base.sha }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}

    - name: Get version
      run: |
        echo ${{ github.event.pull_request.head.sha }}
        chmod +x get-version.py
        ./get-version.py ${{ env.LATEST_MASTER_HASH }}
    - name: Commit and push files
      run: |
        git config --global user.name 'github-actions-bot'
        git add version.txt
        git commit -m "Updating the version" || echo "No changes to version."
        git push
